### ISSUE TITLE
toshitai

### ISSUE THREAD

**Issue by AloneMechanicalTurk** [AyaneSakura/AdventCalendar2016#1]
「佐倉としたい大西」の書き起こしのフォーマットと未書き起こしの回と書き起こしデータの送り先を教えていただけますか．

**Comment by koike** [comment]
書き起こし用の[リポジトリ](https://github.com/toshitai/corpus)を作成しました. PRを投げて頂けると, 確認し次第マージしていこうと思います. 

フォーマットに関しては以下を確認して下さい.
https://github.com/toshitai/corpus/blob/master/README.md

現状は第1回を書き起こしている最中で, それ以外は手を付けられていません.

よろしくお願いします:pray:
